"""
Hermes Agent integration for HPC Pilot.

This module embeds Hermes Agent functionality and extends it with
HPC-specific features.
"""

from __future__ import annotations
import os
import sys
from typing import Optional

def get_home() -> str:
    """Get the HPC Pilot home directory."""
    return os.environ.get("HPC_PILOT_HOME", os.path.expanduser("~/.hpc-pilot"))


def get_config_path() -> str:
    """Get the configuration file path."""
    return os.path.join(get_home(), "config.yaml")


def init_home() -> str:
    """Initialize the HPC Pilot home directory."""
    home = get_home()
    os.makedirs(home, exist_ok=True)
    os.makedirs(os.path.join(home, "skills"), exist_ok=True)
    os.makedirs(os.path.join(home, "sessions"), exist_ok=True)
    os.makedirs(os.path.join(home, "logs"), exist_ok=True)
    return home


def init_config() -> str:
    """Initialize default configuration if it doesn't exist."""
    home = init_home()
    config_path = get_config_path()
    
    if not os.path.exists(config_path):
        default_config = f"""# HPC Pilot Configuration
# Generated by hpc-pilot

model:
  default: anthropic/claude-sonnet-4
  provider: anthropic
  context_length: 128000

agent:
  max_turns: 90
  tool_use_enforcement: auto
  approvals:
    mode: smart

terminal:
  backend: local
  timeout: 300

hpc:
  slurm_bin_dir: /usr/bin
  warewulf_bin_dir: /usr/bin
  spack_root: /opt/spack
  ansible_dir: /etc/hpc-pilot/ansible
  config_repo: /etc/hpc-pilot/config

gateway:
  enabled: true
  port: 8000
  platforms:
    telegram:
      enabled: true
    discord:
      enabled: true
    slack:
      enabled: false

toolsets:
  hpc:
    enabled: true
  web:
    enabled: false

memory:
  memory_enabled: true
  user_profile_enabled: true
  provider: builtin

cron:
  enabled: true

checkpoints:
  enabled: true
  max_snapshots: 50

security:
  redact_secrets: true
"""
        with open(config_path, "w") as f:
            f.write(default_config)
        os.environ["HERMES_CONFIG"] = config_path
        os.environ["HERMES_HOME"] = home
    
    return config_path


def _load_hermes() -> None:
    """Load Hermes Agent with HPC Pilot configuration."""
    # Set up environment
    home = init_home()
    config_path = init_config()
    
    # Set Hermes environment variables
    os.environ["HERMES_CONFIG"] = config_path
    os.environ["HERMES_HOME"] = home
    os.environ["HERMES_PROFILE"] = "default"


def run_cli(args: list[str]) -> int:
    """Run Hermes CLI with HPC Pilot configuration."""
    _load_hermes()
    
    # Import Hermes CLI
    try:
        from hermes_cli.main import main as hermes_main
        return hermes_main(args)
    except ImportError as e:
        print(f"Error loading Hermes Agent: {e}")
        print("\nPlease install hpc-pilot with:")
        print("  pip install -e '.[anthropic]'")
        return 1


def run_agent(query: Optional[str] = None, toolsets: Optional[list[str]] = None) -> int:
    """Run Hermes agent with HPC toolset."""
    _load_hermes()
    
    args = ["chat"]
    if query:
        args.extend(["-q", query])
    if toolsets:
        args.extend(["-t", ",".join(toolsets)])
    
    return run_cli(args)