#!/usr/bin/env python3
"""
HPC Pilot CLI - Standalone AI agent for HPC cluster management.

This is the standalone entrypoint that embeds and extends Hermes Agent.
Users install hpc-pilot and get Hermes Agent capabilities automatically.

Usage:
    hpc-pilot                # Start interactive chat
    hpc-pilot chat           # Start interactive chat (alias)
    hpc-pilot shell          # Start shell session
    hpc-pilot tui            # Start text-based UI
    hpc-pilot gateway        # Start gateway for Telegram/Discord
    hpc-pilot setup          # Initial configuration wizard
    hpc-pilot health         # Check cluster health
    hpc-pilot nodes          # Show node status
    hpc-pilot queue          # Show job queue
    hpc-pilot version        # Show version information
"""

from __future__ import annotations
import sys
import os
import argparse
from typing import Optional

def get_hermes_home() -> str:
    """Get the HPC Pilot home directory."""
    return os.environ.get("HPC_PILOT_HOME", os.path.expanduser("~/.hpc-pilot"))


def get_config_path() -> str:
    """Get the configuration file path."""
    return os.path.join(get_hermes_home(), "config.yaml")


def ensure_home_dir() -> str:
    """Ensure the HPC Pilot home directory exists."""
    home = get_hermes_home()
    os.makedirs(home, exist_ok=True)
    os.makedirs(os.path.join(home, "skills"), exist_ok=True)
    os.makedirs(os.path.join(home, "sessions"), exist_ok=True)
    os.makedirs(os.path.join(home, "logs"), exist_ok=True)
    return home


def init_config() -> None:
    """Initialize default configuration."""
    home = ensure_home_dir()
    config_path = get_config_path()
    
    if not os.path.exists(config_path):
        # Default configuration
        default_config = f"""# HPC Pilot Configuration
# Generated by hpc-pilot

model:
  default: anthropic/claude-sonnet-4
  provider: anthropic
  context_length: 128000

agent:
  max_turns: 90
  tool_use_enforcement: auto
  approvals:
    mode: smart

terminal:
  backend: local
  timeout: 300

hpc:
  slurm_bin_dir: /usr/bin
  warewulf_bin_dir: /usr/bin
  spack_root: /opt/spack
  ansible_dir: /etc/hpc-pilot/ansible
  config_repo: /etc/hpc-pilot/config

gateway:
  enabled: true
  port: 8000
  platforms:
    telegram:
      enabled: true
    discord:
      enabled: true
    slack:
      enabled: false

toolsets:
  hpc:
    enabled: true
  web:
    enabled: false

memory:
  memory_enabled: true
  user_profile_enabled: true
  provider: builtin

cron:
  enabled: true

checkpoints:
  enabled: true
  max_snapshots: 50

security:
  redact_secrets: true
"""
        with open(config_path, "w") as f:
            f.write(default_config)
        print(f"Created default configuration: {config_path}")


def setup_command(args: argparse.Namespace) -> int:
    """Run the setup wizard."""
    home = ensure_home_dir()
    init_config()
    
    print("\n" + "=" * 60)
    print("HPC Pilot Setup Wizard")
    print("=" * 60)
    print(f"\nConfiguration directory: {home}")
    print(f"Configuration file:      {get_config_path()}")
    
    # Try to load Hermes Agent CLI
    try:
        from hpc_pilot._hermes import run_cli
        print("\nStarting Hermes Agent setup...")
        return run_cli(["setup"])
    except ImportError:
        print("\nError: Hermes Agent not found. Please install hpc-pilot properly.")
        print("Run: pip install -e .")
        return 1


def chat_command(args: argparse.Namespace) -> int:
    """Run interactive chat."""
    ensure_home_dir()
    init_config()
    
    try:
        from hpc_pilot._hermes import run_cli
        return run_cli(["chat"])
    except ImportError as e:
        print(f"Error: {e}")
        print("Please install hpc-pilot with: pip install -e '.[anthropic]'")
        return 1


def shell_command(args: argparse.Namespace) -> int:
    """Start shell session."""
    ensure_home_dir()
    init_config()
    
    try:
        from hpc_pilot._hermes import run_cli
        return run_cli(["shell"])
    except ImportError as e:
        print(f"Error: {e}")
        return 1


def tui_command(args: argparse.Namespace) -> int:
    """Start text-based UI."""
    ensure_home_dir()
    init_config()
    
    try:
        from hpc_pilot._hermes import run_cli
        return run_cli(["tui"])
    except ImportError as e:
        print(f"Error: {e}")
        return 1


def gateway_command(args: argparse.Namespace) -> int:
    """Start gateway service."""
    ensure_home_dir()
    init_config()
    
    try:
        from hpc_pilot.gateway import main as gateway_main
        return gateway_main(args)
    except ImportError as e:
        print(f"Error: {e}")
        print("Gateway requires additional dependencies.")
        print("Install with: pip install hpc-pilot[gateway]")
        return 1


def health_command(args: argparse.Namespace) -> int:
    """Check cluster health."""
    ensure_home_dir()
    init_config()
    
    try:
        from hpc_pilot.tools import hpc_cluster_health_check
        health = hpc_cluster_health_check()
        
        import json
        print(json.dumps(health, indent=2, default=str))
        return 0
    except Exception as e:
        print(f"Health check error: {e}")
        return 1


def nodes_command(args: argparse.Namespace) -> int:
    """Show node status."""
    ensure_home_dir()
    
    try:
        from hpc_pilot.tools import hpc_slurm_node_status
        node = getattr(args, "node", None)
        result = hpc_slurm_node_status(node or "")
        print(result)
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


def queue_command(args: argparse.Namespace) -> int:
    """Show job queue."""
    ensure_home_dir()
    
    try:
        from hpc_pilot.tools import hpc_slurm_queue
        filters = {}
        if hasattr(args, "user") and args.user:
            filters["user"] = args.user
        if hasattr(args, "partition") and args.partition:
            filters["partition"] = args.partition
        
        result = hpc_slurm_queue(filters)
        print(result)
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


def qos_command(args: argparse.Namespace) -> int:
    """Manage QOS settings."""
    ensure_home_dir()
    
    try:
        from hpc_pilot.tools import hpc_slurm_qos_modify
        result = hpc_slurm_qos_modify(
            args.name,
            args.max_wall_min if hasattr(args, "max_wall_min") else None
        )
        print(result)
        
        if not getattr(args, "apply", False):
            print("\n⚠️  Use --apply to apply changes")
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


def werewulf_command(args: argparse.Namespace) -> int:
    """Show Warewulf status."""
    ensure_home_dir()
    
    try:
        from hpc_pilot.tools import hpc_warewulf_node_status
        result = hpc_warewulf_node_status()
        print(result)
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


def spack_command(args: argparse.Namespace) -> int:
    """Spack commands."""
    ensure_home_dir()
    
    try:
        from hpc_pilot.tools import (
            hpc_spack_env_list,
            hpc_spack_find,
            hpc_spack_compilers
        )
        
        if hasattr(args, "action") and args.action == "list":
            result = hpc_spack_env_list()
        elif hasattr(args, "action") and args.action == "find":
            result = hpc_spack_find(args.env)
        elif hasattr(args, "action") and args.action == "compilers":
            result = hpc_spack_compilers()
        else:
            result = hpc_spack_env_list()
        
        print(result)
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


def ansible_command(args: argparse.Namespace) -> int:
    """Ansible commands."""
    ensure_home_dir()
    
    try:
        from hpc_pilot.tools import hpc_ansible_playbook_run
        
        result = hpc_ansible_playbook_run(
            args.playbook,
            getattr(args, "limit", None)
        )
        print(result)
        
        if not getattr(args, "apply", False):
            print("\n⚠️  Use --apply to apply changes")
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


def version_command(args: argparse.Namespace) -> int:
    """Show version information."""
    try:
        from hpc_pilot import __version__
        print(f"HPC Pilot {__version__}")
        print("Based on Hermes Agent")
        print(f"Python: {'.'.join(map(str, sys.version_info[:3]))}")
        
        # Check Hermes Agent version
        try:
            import hermes_agent
            print(f"Hermes Agent: {getattr(hermes_agent, '__version__', 'unknown')}")
        except ImportError:
            print("Hermes Agent: embedded")
        
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


def main(argv: Optional[list[str]] = None) -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        prog="hpc-pilot",
        description="HPC Pilot - Standalone AI agent for HPC cluster management"
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # Chat command
    chat_parser = subparsers.add_parser("chat", help="Start interactive chat")
    chat_parser.add_argument("-q", "--query", help="Single query, non-interactive")
    chat_parser.add_argument("-m", "--model", help="Model name")
    chat_parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    chat_parser.set_defaults(func=chat_command)
    
    # Shell command
    shell_parser = subparsers.add_parser("shell", help="Start shell session")
    shell_parser.add_argument("--actor", default="cli-user", help="Operator identity")
    shell_parser.add_argument("--role", default="operator", help="RBAC role")
    shell_parser.set_defaults(func=shell_command)
    
    # TUI command
    tui_parser = subparsers.add_parser("tui", help="Start text-based UI")
    tui_parser.set_defaults(func=tui_command)
    
    # Gateway command
    gateway_parser = subparsers.add_parser("gateway", help="Start gateway service")
    gateway_parser.add_argument("--start", action="store_true", help="Start gateway")
    gateway_parser.add_argument("--stop", action="store_true", help="Stop gateway")
    gateway_parser.add_argument("--status", action="store_true", help="Show status")
    gateway_parser.add_argument("--setup", action="store_true", help="Configure gateway")
    gateway_parser.set_defaults(func=gateway_command)
    
    # Setup command
    setup_parser = subparsers.add_parser("setup", help="Configuration wizard")
    setup_parser.set_defaults(func=setup_command)
    
    # Health command
    health_parser = subparsers.add_parser("health", help="Check cluster health")
    health_parser.set_defaults(func=health_command)
    
    # Nodes command
    nodes_parser = subparsers.add_parser("nodes", help="Show node status")
    nodes_parser.add_argument("node", nargs="?", help="Specific node to query")
    nodes_parser.set_defaults(func=nodes_command)
    
    # Queue command
    queue_parser = subparsers.add_parser("queue", help="Show job queue")
    queue_parser.add_argument("--user", help="Filter by user")
    queue_parser.add_argument("--partition", help="Filter by partition")
    queue_parser.set_defaults(func=queue_command)
    
    # QOS command
    qos_parser = subparsers.add_parser("qos", help="Manage QOS settings")
    qos_parser.add_argument("name", help="QOS name")
    qos_parser.add_argument("--op", default="modify", help="Operation")
    qos_parser.add_argument("--max-wall-min", type=int, help="Maximum wall time in minutes")
    qos_parser.add_argument("--apply", action="store_true", help="Apply changes")
    qos_parser.set_defaults(func=qos_command)
    
    # Warewulf command
    werewulf_parser = subparsers.add_parser("werewulf", help="Show Warewulf status")
    werewulf_parser.set_defaults(func=werewulf_command)
    
    # Spack command
    spack_parser = subparsers.add_parser("spack", help="Spack commands")
    spack_subparsers = spack_parser.add_subparsers(dest="action", help="Spack action")
    spack_list = spack_subparsers.add_parser("list", help="List environments")
    spack_find = spack_subparsers.add_parser("find", help="Find specs")
    spack_find.add_argument("env", help="Environment name")
    spack_compilers = spack_subparsers.add_parser("compilers", help="List compilers")
    spack_parser.set_defaults(func=spack_command)
    
    # Ansible command
    ansible_parser = subparsers.add_parser("ansible", help="Ansible commands")
    ansible_parser.add_argument("playbook", help="Playbook path")
    ansible_parser.add_argument("--limit", help="Host limit")
    ansible_parser.add_argument("--apply", action="store_true", help="Apply changes")
    ansible_parser.add_argument("--check", action="store_true", help="Check mode")
    ansible_parser.set_defaults(func=ansible_command)
    
    # Version command
    version_parser = subparsers.add_parser("version", help="Show version")
    version_parser.set_defaults(func=version_command)
    
    args = parser.parse_args(argv)
    
    if not args.command:
        # Default to chat
        args.command = "chat"
        args.func = chat_command
    
    if hasattr(args, "func"):
        return args.func(args)
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main())