"""Configuration initialization for HPC Pilot."""
from __future__ import annotations

import os

from hpc_pilot.paths import config_path, ensure_layout

DEFAULT_CONFIG = """\
# HPC Pilot Configuration
# Generated by hpc-pilot

model:
  # Model used for the AI agent (hpc-pilot chat / gateway)
  default: claude-opus-4-7
  provider: anthropic

agent:
  max_turns: 90

terminal:
  backend: local
  timeout: 300

hpc:
  slurm_bin_dir: /usr/bin
  warewulf_bin_dir: /usr/bin
  spack_root: /opt/spack
  ansible_dir: /etc/hpc-pilot/ansible
  config_repo: /etc/hpc-pilot/config

gateway:
  enabled: true
  port: 8000
  platforms:
    telegram:
      enabled: true
    discord:
      enabled: true
    slack:
      enabled: false

toolsets:
  hpc:
    enabled: true
  web:
    enabled: false

memory:
  memory_enabled: true
  user_profile_enabled: true
  provider: builtin

cron:
  enabled: true

checkpoints:
  enabled: true
  max_snapshots: 50

security:
  redact_secrets: true
"""


def init_config() -> None:
    """Create the default config file if it does not already exist."""
    ensure_layout()
    path = config_path()
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write(DEFAULT_CONFIG)
