"""Gateway module for HPC Pilot."""

from __future__ import annotations
import os
from typing import Optional

def get_home() -> str:
    """Get the HPC Pilot home directory."""
    return os.environ.get("HPC_PILOT_HOME", os.path.expanduser("~/.hpc-pilot"))


def init_home() -> str:
    """Initialize the HPC Pilot home directory."""
    home = get_home()
    os.makedirs(home, exist_ok=True)
    os.makedirs(os.path.join(home, "skills"), exist_ok=True)
    os.makedirs(os.path.join(home, "sessions"), exist_ok=True)
    os.makedirs(os.path.join(home, "logs"), exist_ok=True)
    return home


def init_config() -> str:
    """Initialize default configuration if it doesn't exist."""
    home = init_home()
    config_path = os.path.join(home, "config.yaml")
    
    if not os.path.exists(config_path):
        default_config = f"""# HPC Pilot Configuration
# Generated by hpc-pilot gateway

model:
  default: anthropic/claude-sonnet-4
  provider: anthropic
  context_length: 128000

agent:
  max_turns: 90
  tool_use_enforcement: auto

terminal:
  backend: local
  timeout: 300

hpc:
  slurm_bin_dir: /usr/bin
  warewulf_bin_dir: /usr/bin
  spack_root: /opt/spack
  ansible_dir: /etc/hpc-pilot/ansible
  config_repo: /etc/hpc-pilot/config

gateway:
  enabled: true
  port: 8000
  platforms:
    telegram:
      enabled: true
    discord:
      enabled: true
    slack:
      enabled: false

toolsets:
  hpc:
    enabled: true

memory:
  memory_enabled: true
  user_profile_enabled: true
  provider: builtin

cron:
  enabled: true

checkpoints:
  enabled: true
  max_snapshots: 50

security:
  redact_secrets: true
"""
        with open(config_path, "w") as f:
            f.write(default_config)
    
    return config_path


def main(argv: Optional[list[str]] = None) -> int:
    """Main entry point for gateway."""
    import sys
    import argparse
    
    parser = argparse.ArgumentParser(
        prog="hpc-pilot-gateway",
        description="HPC Pilot Gateway - Web server for HPC cluster management"
    )
    
    parser.add_argument(
        "--start", action="store_true",
        help="Start gateway server"
    )
    parser.add_argument(
        "--stop", action="store_true",
        help="Stop gateway server"
    )
    parser.add_argument(
        "--status", action="store_true",
        help="Show gateway status"
    )
    parser.add_argument(
        "--setup", action="store_true",
        help="Configure gateway"
    )
    parser.add_argument(
        "--port", type=int, default=8000,
        help="Port to run gateway on (default: 8000)"
    )
    parser.add_argument(
        "--host", type=str, default="127.0.0.1",
        help="Host to bind to (default: 127.0.0.1)"
    )
    
    args = parser.parse_args(argv)
    
    # Initialize home directory and config
    init_home()
    init_config()
    
    # Set environment variables
    os.environ["HPC_PILOT_HOME"] = get_home()
    
    if args.setup:
        print("Gateway setup:")
        print("  1. Configure platform tokens in ~/.hpc-pilot/.env")
        print("  2. Edit ~/.hpc-pilot/config.yaml for platform settings")
        print("  3. Start gateway with: hpc-pilot gateway --start")
        return 0
    
    if args.stop:
        print("Stopping gateway...")
        # TODO: Implement stop logic
        print("Gateway stopped.")
        return 0
    
    if args.status:
        print("Gateway status: checking...")
        # TODO: Implement status check
        print("Gateway is running (placeholder).")
        return 0
    
    # Default: start gateway
    if args.start or not any([args.stop, args.status, args.setup]):
        print(f"Starting HPC Pilot Gateway on {args.host}:{args.port}")
        print(f"Visit http://localhost:{args.port} in your browser")
        print("\nSupported platforms:")
        print("  - Telegram (requires TELEGRAM_BOT_TOKEN)")
        print("  - Discord (requires DISCORD_BOT_TOKEN)")
        print("  - Slack (requires SLACK_BOT_TOKEN)")
        
        # Try to start the gateway server
        try:
            # Import Hermes gateway
            from hermes_cli.gateway import main as gateway_main
            return gateway_main(["run", "--port", str(args.port)])
        except ImportError:
            print("\nGateway requires Hermes Agent gateway support.")
            print("Install with: pip install hpc-pilot[gateway]")
            print("\nAlternative: Use hpc-pilot CLI directly")
            return 1